### PR TITLE
Added licensee tab changes

### PR DESCRIPTION
**Pull request by porta-antiporta**
- [ ] Cleanup of list view
- [ ] Added address search input
- [ ] Licensee address label to match Tax ID

### CODE REVIEW

**Comment by porta-antiporta** [comment]
@Jkrzy I assume you meant [this comment](https://github.com/USKPA-dev/uskpa/pull/177#issuecomment-393003136) to be on this PR instead of #177?

It's "intentional" in the sense that I was intending to inherit that styling from the certificates listview.  #notadesigner so unsure what the styling guide for that is.

**Comment by Jkrzy** [comment]
looking good, thanks for jumping in!

The first column of each table here has no bottom-border, is that intentional?

**Comment by Jkrzy** [comment]
cc @porta-antiporta, @theresaanna.

It looks like that missing border may have been unintentional as it doesn't match our original search mock-up. I added a small tweak here to have the border extend across all table cells.

**Comment by porta-antiporta** [comment]
👍 :shipit:

**Pull request merged**
